services:
  php:
    image: "bigtruedata/php-mysqli"
    network_mode: "host"
    volumes:
      - './php/src:/home'
    depends_on:
      - mysql
    command: bash -c "cd /home; php -S localhost:28081;"

  mysql:
    build: "./mysql"
    ports:
      - "127.0.0.1:13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "verysecurerootpasswordiclassTECHtessolution12345672019docker"
      MYSQL_USER: mysql
      MYSQL_PASSWORD: "someothersecurepassword0123456"

  pma:
    image: "phpmyadmin/phpmyadmin:latest"
    ports:
      - "127.0.0.1:18080:80"
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: 3306
    depends_on:
      - mysql
